[workspace]
resolver = "3"
members = [
    "src/hotcode",
    "src/hotcode_core",
    "src/hotcode_proc_macro"
]

[workspace.dependencies]
hotcode = { version = "0.1.5", path = "src/hotcode" }
hotcode_core = { version = "0.1.5", path = "src/hotcode_core" }
hotcode_proc_macro = { version = "0.1.5", path = "src/hotcode_proc_macro" }

proc-macro2 = { version = "1.0.95", features = ["span-locations"] }
quote = "1.0.40"
syn = { version = "3.0.5", features = ["full"] }
not_enough_syntax = "0.1.7"

libloading = "0.9.0"
indexmap = "2.14.2"
arc-swap = "1.9.2"
notify-debouncer-full = "0.7.0"
libc = "0.2.189"
winapi = "0.3.9"

automock = "0.2.3"
tempfile = "3.27.0"
dircpy = "0.3.20"
