[package]
name = "hotcode"
version = "0.1.1"
edition = "2024"
rust-version = "1.89.0"
description = "Library for hotreload in Rust."
license = "MIT"
repository = "https://github.com/alordash/hotcode"
readme = "../../README.md"

[dependencies]
hotcode_core = { workspace = true }
hotcode_proc_macro = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
dircpy = { workspace = true }

[lints.clippy]
needless_return = "allow"
match_like_matches_macro = "allow"
