[package]
name = "hotcode_core"
version = "0.1.4"
edition = "2024"
rust-version = "1.89.0"
description = "Core for hotcode library."
license = "MIT"
repository = "https://github.com/alordash/hotcode"
readme = "../../README.md"

[dependencies]
indexmap = { workspace = true }
libloading = { workspace = true }
arc-swap = { workspace = true }
notify-debouncer-full = { workspace = true }

[dev-dependencies]
automock = { workspace = true }

[lints.clippy]
needless_return = "allow"
match_like_matches_macro = "allow"

[target.'cfg(windows)'.dependencies]
winapi = { workspace = true, features = ["libloaderapi", "minwindef", "winnt"] }

[target.'cfg(unix)'.dependencies]
libc = { workspace = true }